version: '3.7'
services:
  arduino-builder:
    build:
      context: .
      target: arduino-builder
    image: arduino-builder
    command: scripts/build-project.sh $CORE $BOARD
    volumes:
        - "../:/build"
  docs-builder:
    build:
      context: .
      target: docs-builder
    image: docs-builder
    command: scripts/build-docs.sh
    volumes:
        - "../:/build"
