version: '3.7'
services:
  arduino-builder:
    build:
      context: .
      target: arduino-builder
    image: gaggiapidcontroller/arduino-builder
    command: scripts/build-project.sh $CORE $BOARD
    user: $UID:$GID
    volumes:
        - "../:/build"
  docs-builder:
    build:
      context: .
      target: docs-builder
    image: gaggiapidcontroller/docs-builder
    command: make -C docs html
    user: $UID:$GID
    volumes:
        - "../:/build"
