name: CI pipeline

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true


      - name: Build
        run: make ci
